@wakuwakuApi.Version = 1
@wakuwakuApi.Port = 7140
@wakuwakuApi.HostAddress = https://localhost:{{wakuwakuApi.Port}}/api/v{{wakuwakuApi.Version}}

GET {{wakuwakuApi.HostAddress}}/category/
Accept: application/json

###

POST {{wakuwakuApi.HostAddress}}/category/
Accept: application/json
Content-Type: application/json

{
  "name": "Languaje",
  "description": "Categoría relacionada con idiomas."
}
###
